<?php
/** @var yii\web\View $this */
/** @var app\models\UpdatePasswordForm $model */

use yii\bootstrap5\ActiveForm;
use yii\bootstrap5\Html;
use yii\helpers\Url;
use yii\web\View;

/**
 * Page title and breadcrumbs.
 */
$this->title = 'Update Password - CAN';
$this->params['breadcrumbs'][] = ['label' => 'Account', 'url' => ['site/profile']];
$this->params['breadcrumbs'][] = $this->title;

/**
 * Prepare navigation URLs.
 */
$profileUrl = Url::to(['site/profile']);
$backUrl = Yii::$app->request->referrer ?: $profileUrl;

/**
 * Prepare input IDs generated by Yii.
 * These IDs are used by JavaScript for validation and password visibility.
 */
$oldPasswordInputId = Html::getInputId($model, 'old_password');
$newPasswordInputId = Html::getInputId($model, 'new_password');
$confirmPasswordInputId = Html::getInputId($model, 'confirm_password');

/**
 * Register Yii asset.
 */
\yii\web\YiiAsset::register($this);

/**
 * Register Bootstrap Icons.
 */
$this->registerCssFile(
    'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css',
    ['position' => View::POS_HEAD]
);

/**
 * Register RemixIcon.
 */
$this->registerCssFile(
    'https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css',
    ['rel' => 'stylesheet', 'position' => View::POS_HEAD]
);

/**
 * Register SweetAlert2 CSS and JS.
 */
$this->registerCssFile(
    'https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css',
    ['position' => View::POS_HEAD]
);

$this->registerJsFile(
    'https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js',
    ['depends' => [\yii\web\JqueryAsset::class]]
);

/**
 * Register page CSS.
 * This page follows the same card-based design used by AO/MRO Profile update pages.
 */
$this->registerCss(<<<CSS
html,
body {
    max-width: 100%;
    overflow-x: hidden;
}

.create-page {
    padding: 24px;
    background: #f5f7fb;
    min-height: 100vh;
    max-width: 100%;
    overflow-x: hidden;
}

.create-page .container-fluid {
    max-width: 1180px;
    overflow-x: hidden;
    padding-left: 0;
    padding-right: 0;
    margin: 0 auto;
}

.page-header-card {
    background: linear-gradient(135deg, #ffffff, #eef4ff);
    border-radius: 18px;
    padding: 22px 26px;
    margin-bottom: 22px;
    box-shadow: 0 8px 24px rgba(15, 23, 42, 0.08);
    border: 1px solid #e5eaf3;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 15px;
    flex-wrap: wrap;
}

.dash-title {
    margin: 0;
    font-size: 28px;
    font-weight: 800;
    color: #1f2937;
}

.subtitle-text {
    color: #6b7280;
    margin-top: 6px;
    font-size: 14px;
}

.header-actions {
    display: flex;
    align-items: center;
    gap: 10px;
    flex-wrap: wrap;
}

.btn-page-action {
    border-radius: 9px;
    padding: 10px 18px;
    font-weight: 800;
    font-size: 13px;
    display: inline-flex;
    align-items: center;
    gap: 7px;
    white-space: nowrap;
    text-decoration: none;
    transition: all .2s ease;
}

.btn-back {
    background: #ffffff;
    color: #334155 !important;
    border: 1px solid #cbd5e1;
}

.btn-back:hover {
    background: #f1f5f9;
    color: #0f172a !important;
    transform: translateY(-1px);
    text-decoration: none;
}

.form-layout {
    display: grid;
    grid-template-columns: 1.12fr 0.88fr;
    gap: 18px;
    align-items: start;
}

.form-card,
.helper-card {
    background: #ffffff;
    border-radius: 18px;
    padding: 20px;
    box-shadow: 0 8px 24px rgba(15, 23, 42, 0.08);
    border: 1px solid #e5eaf3;
    max-width: 100%;
}

.section-title {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 0 0 18px;
    font-size: 17px;
    font-weight: 900;
    color: #0f172a;
}

.brand-panel {
    display: flex;
    align-items: center;
    gap: 14px;
    background: #f8fafc;
    border: 1px solid #e5eaf3;
    border-radius: 16px;
    padding: 14px;
    margin-bottom: 18px;
}

.brand-logo-box {
    width: 78px;
    height: 78px;
    min-width: 78px;
    border-radius: 16px;
    background: #ffffff;
    border: 1px solid #e5eaf3;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
}

.brand-logo-box img {
    max-width: 68px;
    max-height: 68px;
    object-fit: contain;
}

.brand-panel-title {
    color: #0f172a;
    font-size: 15px;
    font-weight: 900;
    margin: 0;
}

.brand-panel-text {
    color: #64748b;
    font-size: 13px;
    font-weight: 700;
    line-height: 1.45;
    margin: 4px 0 0;
}

.form-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 16px;
}

.form-field-card {
    background: #f8fafc;
    border: 1px solid #e5eaf3;
    border-radius: 14px;
    padding: 14px;
    min-width: 0;
}

.form-field-card.full-width {
    grid-column: 1 / -1;
}

.field-heading {
    display: flex;
    align-items: center;
    gap: 7px;
    color: #64748b;
    font-size: 12px;
    font-weight: 900;
    text-transform: uppercase;
    letter-spacing: .04em;
    margin-bottom: 8px;
}

.field-heading i {
    color: #f59e0b;
    font-size: 15px;
}

.required-mark {
    color: #dc2626;
    font-size: 14px;
    line-height: 1;
}

.form-group {
    margin-bottom: 0;
}

.form-group label,
.control-label,
.form-label {
    display: none;
}

.form-control {
    width: 100%;
    min-height: 46px;
    border-radius: 12px !important;
    border: 1px solid #cbd5e1 !important;
    background-color: #ffffff !important;
    color: #0f172a !important;
    font-size: 14px;
    font-weight: 700;
    padding: 10px 13px;
    box-shadow: none !important;
    transition: all .2s ease;
}

.form-control:focus {
    border-color: #f59e0b !important;
    box-shadow: 0 0 0 4px rgba(245, 158, 11, 0.14) !important;
}

.help-block,
.invalid-feedback {
    margin-top: 7px;
    font-size: 12px;
    font-weight: 700;
    color: #dc2626;
}

.has-error .form-control,
.is-invalid {
    border-color: #fca5a5 !important;
}

.is-valid {
    border-color: #86efac !important;
}

.password-field-wrap {
    position: relative;
}

.password-field-wrap .form-control {
    padding-right: 48px;
}

.password-toggle-btn {
    position: absolute;
    top: 50%;
    right: 12px;
    transform: translateY(-50%);
    width: 34px;
    height: 34px;
    border: 0;
    border-radius: 10px;
    background: #f8fafc;
    color: #64748b;
    font-size: 19px;
    line-height: 1;
    padding: 0;
    cursor: pointer;
    z-index: 5;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    transition: all .2s ease;
}

.password-toggle-btn:hover,
.password-toggle-btn:focus {
    outline: none;
    background: #fff7ed;
    color: #c2410c;
}

.password-strength {
    grid-column: 1 / -1;
    display: none;
    background: #f8fafc;
    border: 1px solid #e5eaf3;
    border-radius: 14px;
    padding: 12px 14px;
    margin: 0;
}

.password-strength-track {
    height: 8px;
    width: 100%;
    overflow: hidden;
    border-radius: 999px;
    background: #e5eaf3;
}

.password-strength-bar {
    height: 100%;
    width: 0;
    border-radius: 999px;
    transition: all .2s ease;
}

.password-strength-bar.weak {
    background: #f97316;
}

.password-strength-bar.medium {
    background: #eab308;
}

.password-strength-bar.strong {
    background: #22c55e;
}

.password-strength-label {
    display: block;
    margin-top: 8px;
    color: #64748b;
    font-size: 12px;
    font-weight: 800;
}

.password-status,
.password-submit-hint {
    grid-column: 1 / -1;
    border-radius: 14px;
    padding: 12px 14px;
    font-size: 13px;
    font-weight: 800;
    margin: 0;
}

.password-status.d-none,
.password-submit-hint.d-none {
    display: none !important;
}

.password-status.text-success {
    background: #dcfce7;
    color: #166534 !important;
    border: 1px solid #bbf7d0;
}

.password-status.text-danger,
.password-submit-hint {
    background: #fee2e2;
    color: #991b1b !important;
    border: 1px solid #fecaca;
}

.form-actions {
    margin-top: 20px;
    padding-top: 18px;
    border-top: 1px solid #e5eaf3;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: 10px;
    flex-wrap: wrap;
}

.btn-form-action {
    min-height: 44px;
    border-radius: 12px;
    padding: 11px 18px;
    font-size: 13px;
    font-weight: 900;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    text-decoration: none;
    border: 1px solid rgba(15, 23, 42, .12);
    transition: all .2s ease;
}

.btn-update {
    background: #f59e0b;
    color: #ffffff !important;
    box-shadow: 0 8px 18px rgba(245, 158, 11, 0.24);
}

.btn-update:hover:not(:disabled) {
    background: #d97706;
    color: #ffffff !important;
    transform: translateY(-1px);
    text-decoration: none;
}

.btn-update:disabled {
    opacity: .55;
    cursor: not-allowed;
    transform: none;
    box-shadow: none;
}

.btn-cancel,
.btn-reset {
    background: #64748b;
    color: #ffffff !important;
    box-shadow: 0 8px 18px rgba(100, 116, 139, 0.18);
}

.btn-cancel:hover,
.btn-reset:hover {
    background: #475569;
    color: #ffffff !important;
    transform: translateY(-1px);
    text-decoration: none;
}

.alert {
    border-radius: 14px;
    border: none;
    font-weight: 800;
    padding: 14px 16px;
    margin-bottom: 18px;
}

.alert-success {
    background: #dcfce7;
    color: #166534;
    border: 1px solid #bbf7d0;
}

.alert-danger {
    background: #fee2e2;
    color: #991b1b;
    border: 1px solid #fecaca;
}

.helper-list {
    display: grid;
    gap: 12px;
}

.helper-item {
    background: #f8fafc;
    border: 1px solid #e5eaf3;
    border-radius: 14px;
    padding: 14px;
}

.helper-label {
    display: flex;
    align-items: center;
    gap: 7px;
    color: #0f172a;
    font-size: 13px;
    font-weight: 900;
    margin-bottom: 5px;
}

.helper-label i {
    color: #f59e0b;
}

.helper-text {
    color: #64748b;
    font-size: 13px;
    font-weight: 700;
    line-height: 1.5;
    margin: 0;
}

.swal-update-popup {
    width: 380px !important;
    border-radius: 18px !important;
    padding: 22px !important;
}

.swal-update-title {
    font-size: 20px !important;
    font-weight: 900 !important;
    color: #0f172a !important;
}

.swal-update-html {
    font-size: 14px !important;
    font-weight: 700 !important;
    color: #64748b !important;
}

.swal-update-confirm {
    border-radius: 10px !important;
    padding: 10px 18px !important;
    font-size: 13px !important;
    font-weight: 900 !important;
    background: #f59e0b !important;
    color: #ffffff !important;
    box-shadow: 0 8px 18px rgba(245, 158, 11, 0.25) !important;
}

.swal-update-confirm:hover {
    background: #d97706 !important;
}

.swal-update-cancel {
    border-radius: 10px !important;
    padding: 10px 18px !important;
    font-size: 13px !important;
    font-weight: 900 !important;
    background: #64748b !important;
}

.swal2-actions {
    gap: 12px !important;
}

@media (max-width: 992px) {
    .create-page {
        padding: 14px;
    }

    .page-header-card {
        padding: 18px;
    }

    .dash-title {
        font-size: 23px;
    }

    .form-layout {
        grid-template-columns: 1fr;
    }

    .form-grid {
        grid-template-columns: 1fr;
    }
}

@media (max-width: 576px) {
    .create-page {
        padding: 10px;
    }

    .page-header-card,
    .form-card,
    .helper-card {
        border-radius: 14px;
        padding: 16px;
    }

    .brand-panel {
        flex-direction: column;
        align-items: flex-start;
    }

    .header-actions,
    .btn-page-action,
    .btn-form-action {
        width: 100%;
    }

    .form-actions {
        justify-content: stretch;
    }
}
CSS);
?>

<main class="dash-content create-page">
    <div class="container-fluid">

        <!-- Page header -->
        <div class="page-header-card">
            <div>
                <h1 class="dash-title">
                    <span style="color: #f59e0b;">
                        <i class="bi bi-shield-lock"></i>
                    </span>
                    <?= Html::encode($this->title) ?>
                </h1>

                <div class="subtitle-text">
                    Update your current password and keep your CAN account secure.
                </div>
            </div>

            <div class="header-actions">
                <?= Html::a(
                    '<i class="bi bi-arrow-left-circle"></i> Back to Profile',
                    $backUrl,
                    ['class' => 'btn-page-action btn-back']
                ) ?>
            </div>
        </div>

        <!-- Flash messages -->
        <?php if (Yii::$app->session->hasFlash('success')): ?>
            <div class="alert alert-success">
                <i class="bi bi-check-circle"></i>
                <?= Html::encode(Yii::$app->session->getFlash('success')) ?>
            </div>
        <?php endif; ?>

        <?php if (Yii::$app->session->hasFlash('error')): ?>
            <div class="alert alert-danger">
                <i class="bi bi-exclamation-triangle"></i>
                <?= Html::encode(Yii::$app->session->getFlash('error')) ?>
            </div>
        <?php endif; ?>

        <div class="form-layout">

            <!-- Main update password form -->
            <div class="form-card">
                <h2 class="section-title">
                    <i class="bi bi-pencil-square text-warning"></i>
                    Password Information
                </h2>

                <!-- Brand block -->
                <div class="brand-panel">
                    <div class="brand-logo-box">
                        <img
                            src="<?= Yii::getAlias('@web/logo/can-logo-main.png') ?>"
                            alt="CAN - Core Aviation Network"
                        >
                    </div>
                    <div>
                        <p class="brand-panel-title">Core Aviation Network</p>
                        <p class="brand-panel-text">
                            Enter your current password, then choose and confirm a strong new password.
                        </p>
                    </div>
                </div>

                <?php $form = ActiveForm::begin([
                    'id' => 'update-password-form',
                    'options' => ['novalidate' => true],
                    'fieldConfig' => [
                        'labelOptions' => ['class' => 'form-label'],
                        'errorOptions' => ['class' => 'invalid-feedback'],
                        'options' => ['class' => 'form-group'],
                    ],
                ]); ?>

                <div class="form-grid">

                    <!-- Current password -->
                    <div class="form-field-card full-width">
                        <div class="field-heading">
                            <i class="bi bi-key"></i>
                            Current password
                            <span class="required-mark">*</span>
                        </div>

                        <?= $form->field($model, 'old_password', [
                            'template' => "<div class=\"password-field-wrap\">{input}\n                                <button type=\"button\" class=\"password-toggle-btn\" data-target=\"{$oldPasswordInputId}\" aria-label=\"Show current password\">\n                                    <i class=\"ri-eye-line\"></i>\n                                </button>\n                            </div>\n{error}",
                        ])->passwordInput([
                            'id' => $oldPasswordInputId,
                            'class' => 'form-control',
                            'placeholder' => 'Enter your current password',
                            'autocomplete' => 'current-password',
                            'required' => true,
                        ]) ?>
                    </div>

                    <!-- New password -->
                    <div class="form-field-card full-width">
                        <div class="field-heading">
                            <i class="bi bi-lock"></i>
                            New password
                            <span class="required-mark">*</span>
                        </div>

                        <?= $form->field($model, 'new_password', [
                            'template' => "<div class=\"password-field-wrap\">{input}\n                                <button type=\"button\" class=\"password-toggle-btn\" data-target=\"{$newPasswordInputId}\" aria-label=\"Show new password\">\n                                    <i class=\"ri-eye-line\"></i>\n                                </button>\n                            </div>\n{error}",
                        ])->passwordInput([
                            'id' => $newPasswordInputId,
                            'class' => 'form-control',
                            'placeholder' => 'Choose a new password',
                            'autocomplete' => 'new-password',
                            'required' => true,
                            'minlength' => 8,
                            'aria-describedby' => 'password-length-message',
                        ]) ?>

                        <!-- Live password length message -->
                        <div id="password-length-message" class="password-status d-none"></div>
                    </div>

                    <!-- Password strength meter -->
                    <div id="password-strength" class="password-strength">
                        <div class="password-strength-track">
                            <div class="password-strength-bar"></div>
                        </div>

                        <span class="password-strength-label">
                            Password strength: —
                        </span>
                    </div>

                    <!-- Confirm password -->
                    <div class="form-field-card full-width">
                        <div class="field-heading">
                            <i class="bi bi-unlock"></i>
                            Confirm password
                            <span class="required-mark">*</span>
                        </div>

                        <?= $form->field($model, 'confirm_password', [
                            'template' => "<div class=\"password-field-wrap\">{input}\n                                <button type=\"button\" class=\"password-toggle-btn\" data-target=\"{$confirmPasswordInputId}\" aria-label=\"Show confirm password\">\n                                    <i class=\"ri-eye-line\"></i>\n                                </button>\n                            </div>\n{error}",
                        ])->passwordInput([
                            'id' => $confirmPasswordInputId,
                            'class' => 'form-control',
                            'placeholder' => 'Re-enter the new password',
                            'autocomplete' => 'new-password',
                            'required' => true,
                        ]) ?>
                    </div>

                    <!-- Live password match message -->
                    <div id="password-match-message" class="password-status d-none"></div>

                    <!-- Helper shown when submit is disabled -->
                    <div id="password-submit-hint" class="password-submit-hint d-none">
                        Complete all password fields correctly to enable the update button.
                    </div>
                </div>

                <!-- Form action buttons -->
                <div class="form-actions">
                    <?= Html::button(
                        '<i class="bi bi-arrow-counterclockwise"></i> Reset Form',
                        [
                            'class' => 'btn-form-action btn-reset',
                            'id' => 'reset-password-form',
                            'type' => 'button',
                        ]
                    ) ?>

                    <!-- <?= Html::a(
                        '<i class="bi bi-x-circle"></i> Cancel',
                        $profileUrl,
                        ['class' => 'btn-form-action btn-cancel']
                    ) ?> -->

                    <?= Html::submitButton(
                        '<i class="bi bi-check-circle"></i> Update Password',
                        [
                            'class' => 'btn-form-action btn-update',
                            'id' => 'submit-password-button',
                            'disabled' => true,
                        ]
                    ) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>

            <!-- Helper card -->
            <div class="helper-card">
                <h2 class="section-title">
                    <i class="bi bi-info-circle text-warning"></i>
                    Password Guidelines
                </h2>

                <div class="helper-list">
                    <div class="helper-item">
                        <div class="helper-label">
                            <i class="bi bi-shield-check"></i>
                            Use at least 8 characters
                        </div>
                        <p class="helper-text">
                            A longer password is harder to guess and offers better account protection.
                        </p>
                    </div>

                    <div class="helper-item">
                        <div class="helper-label">
                            <i class="bi bi-stars"></i>
                            Mix character types
                        </div>
                        <p class="helper-text">
                            Combine uppercase letters, lowercase letters, numbers and special characters.
                        </p>
                    </div>

                    <div class="helper-item">
                        <div class="helper-label">
                            <i class="bi bi-eye-slash"></i>
                            Keep it private
                        </div>
                        <p class="helper-text">
                            Do not reuse this password on another platform and never share it with other users.
                        </p>
                    </div>

                    <div class="helper-item">
                        <div class="helper-label">
                            <i class="bi bi-check2-circle"></i>
                            Confirm before saving
                        </div>
                        <p class="helper-text">
                            The update button becomes active only when all fields are valid and both new passwords match.
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</main>

<?php
/**
 * Register page JavaScript.
 * Keeps the original behavior: visibility toggle, strength meter, live validation and reset action.
 * Adds SweetAlert confirmation before the final password update.
 */
$js = <<<JS
(function(){
    const form = document.getElementById('update-password-form');
    const oldPassword = document.getElementById('$oldPasswordInputId');
    const newPassword = document.getElementById('$newPasswordInputId');
    const confirmPassword = document.getElementById('$confirmPasswordInputId');
    const strengthBox = document.getElementById('password-strength');
    const strengthBar = document.querySelector('.password-strength-bar');
    const strengthLabel = document.querySelector('.password-strength-label');
    const lengthMessage = document.getElementById('password-length-message');
    const matchMessage = document.getElementById('password-match-message');
    const submitBtn = document.getElementById('submit-password-button');
    const minPasswordLength = 8;
    const submitHint = document.getElementById('password-submit-hint');
    const resetBtn = document.getElementById('reset-password-form');

    if (!form || !oldPassword || !newPassword || !confirmPassword || !submitBtn) {
        return;
    }

    function computePasswordStrength(password) {
        let score = 0;

        if (!password) {
            return {
                level: '',
                width: '0%',
                label: 'Password strength: —'
            };
        }

        if (password.length >= minPasswordLength) score++;
        if (/[a-z]/.test(password)) score++;
        if (/[A-Z]/.test(password)) score++;
        if (/[0-9]/.test(password)) score++;
        if (/[^A-Za-z0-9]/.test(password)) score++;

        if (score <= 2) {
            return {
                level: 'weak',
                width: '33%',
                label: 'Password strength: Weak'
            };
        }

        if (score <= 4) {
            return {
                level: 'medium',
                width: '66%',
                label: 'Password strength: Medium'
            };
        }

        return {
            level: 'strong',
            width: '100%',
            label: 'Password strength: Strong'
        };
    }

    function updatePasswordStrength() {
        if (!strengthBox || !strengthBar || !strengthLabel) {
            return;
        }

        const value = newPassword.value;

        if (!value) {
            strengthBox.style.display = 'none';
            strengthBar.style.width = '0%';
            strengthBar.className = 'password-strength-bar';
            strengthLabel.textContent = 'Password strength: —';
            return;
        }

        const result = computePasswordStrength(value);

        strengthBox.style.display = 'block';
        strengthBar.className = 'password-strength-bar ' + result.level;
        strengthBar.style.width = result.width;
        strengthLabel.textContent = result.label;
    }

    function setInputState(input, isValid, showState) {
        if (!input) {
            return;
        }

        input.classList.remove('is-valid', 'is-invalid');

        if (!showState) {
            return;
        }

        input.classList.add(isValid ? 'is-valid' : 'is-invalid');
    }

    function validatePasswordForm(showMessages) {
        const oldValue = oldPassword.value.trim();
        const newValue = newPassword.value;
        const confirmValue = confirmPassword.value;

        const oldTouched = oldValue.length > 0;
        const newTouched = newValue.length > 0;
        const confirmTouched = confirmValue.length > 0;

        const oldValid = oldValue.length > 0;
        const newValid = newValue.length >= minPasswordLength;
        const confirmValid = confirmTouched && confirmValue === newValue;
        const formValid = oldValid && newValid && confirmValid;

        setInputState(oldPassword, oldValid, showMessages || oldTouched);
        setInputState(newPassword, newValid, showMessages || newTouched);
        setInputState(confirmPassword, confirmValid, showMessages || confirmTouched);

        if (lengthMessage) {
            lengthMessage.className = 'password-status d-none';
            lengthMessage.innerHTML = '';

            if (newTouched && !newValid) {
                lengthMessage.className = 'password-status text-danger';
                lengthMessage.innerHTML = '<i class="ri-error-warning-line"></i> Password length is not valid. Minimum required: ' + minPasswordLength + ' characters. Current length: ' + newValue.length + '/' + minPasswordLength + '.';
            } else if (newTouched && newValid) {
                lengthMessage.className = 'password-status text-success';
                lengthMessage.innerHTML = '<i class="ri-check-line"></i> Password length is valid.';
            } else if (showMessages) {
                lengthMessage.className = 'password-status text-danger';
                lengthMessage.innerHTML = '<i class="ri-error-warning-line"></i> Please enter a new password with at least ' + minPasswordLength + ' characters.';
            }
        }

        if (matchMessage) {
            matchMessage.className = 'password-status d-none';
            matchMessage.innerHTML = '';

            if (confirmTouched) {
                if (confirmValid) {
                    matchMessage.className = 'password-status text-success';
                    matchMessage.innerHTML = '<i class="ri-check-line"></i> Passwords match. You can safely update your password.';
                } else {
                    matchMessage.className = 'password-status text-danger';
                    matchMessage.innerHTML = '<i class="ri-error-warning-line"></i> Passwords do not match. Please enter the same new password.';
                }
            } else if (showMessages) {
                matchMessage.className = 'password-status text-danger';
                matchMessage.innerHTML = '<i class="ri-error-warning-line"></i> Please confirm your new password.';
            }
        }

        submitBtn.disabled = !formValid;

        if (submitHint) {
            submitHint.classList.toggle('d-none', formValid);
        }

        return formValid;
    }

    function initPasswordToggle() {
        const toggleButtons = document.querySelectorAll('.password-toggle-btn');

        toggleButtons.forEach(function(button){
            button.addEventListener('click', function(){
                const targetId = button.getAttribute('data-target');
                const input = document.getElementById(targetId);
                const icon = button.querySelector('i');

                if (!input || !icon) {
                    return;
                }

                const isHidden = input.getAttribute('type') === 'password';

                input.setAttribute('type', isHidden ? 'text' : 'password');

                icon.classList.toggle('ri-eye-line', !isHidden);
                icon.classList.toggle('ri-eye-off-line', isHidden);

                button.setAttribute(
                    'aria-label',
                    isHidden ? 'Hide password' : 'Show password'
                );
            });
        });
    }

    function resetPasswordForm() {
        form.reset();
        form.dataset.updateConfirmed = 'false';

        document.querySelectorAll('.password-toggle-btn').forEach(function(button){
            const targetId = button.getAttribute('data-target');
            const input = document.getElementById(targetId);
            const icon = button.querySelector('i');

            if (input) {
                input.setAttribute('type', 'password');
            }

            if (icon) {
                icon.classList.add('ri-eye-line');
                icon.classList.remove('ri-eye-off-line');
            }
        });

        [oldPassword, newPassword, confirmPassword].forEach(function(input){
            if (input) {
                input.classList.remove('is-valid', 'is-invalid');
            }
        });

        if (strengthBox && strengthBar && strengthLabel) {
            strengthBox.style.display = 'none';
            strengthBar.style.width = '0%';
            strengthBar.className = 'password-strength-bar';
            strengthLabel.textContent = 'Password strength: —';
        }

        if (lengthMessage) {
            lengthMessage.className = 'password-status d-none';
            lengthMessage.innerHTML = '';
        }

        if (matchMessage) {
            matchMessage.className = 'password-status d-none';
            matchMessage.innerHTML = '';
        }

        if (submitHint) {
            submitHint.classList.add('d-none');
        }

        submitBtn.disabled = true;
    }

    function initSubmitConfirmation() {
        form.addEventListener('submit', function(event){
            if (form.dataset.updateConfirmed === 'true') {
                return true;
            }

            updatePasswordStrength();

            if (!validatePasswordForm(true)) {
                event.preventDefault();

                const firstInvalid = form.querySelector('.is-invalid');

                let alertMessage = 'Please complete all password fields correctly before updating your password.';

                if (newPassword.value.length > 0 && newPassword.value.length < minPasswordLength) {
                    alertMessage = 'Your new password length is not valid. It must contain at least ' + minPasswordLength + ' characters.';
                }

                Swal.fire({
                    title: 'Invalid password information',
                    html: alertMessage,
                    icon: 'warning',
                    confirmButtonText: '<i class="bi bi-check-circle"></i> Got it',
                    customClass: {
                        popup: 'swal-update-popup',
                        title: 'swal-update-title',
                        htmlContainer: 'swal-update-html',
                        confirmButton: 'swal-update-confirm'
                    }
                }).then(function(){
                    if (firstInvalid) {
                        firstInvalid.focus();
                    }
                });

                return false;
            }

            event.preventDefault();

            Swal.fire({
                title: 'Confirm password update?',
                html: 'Please confirm that you want to update your account password.',
                icon: 'warning',
                showCancelButton: true,
                // FORM DIALOG ACTIONS: identify the exact action and offer review.
                confirmButtonText: '<i class="bi bi-shield-lock"></i> Update password',
                cancelButtonText: '<i class="bi bi-arrow-counterclockwise"></i> Review',
                reverseButtons: true,
                focusCancel: true,
                customClass: {
                    popup: 'swal-update-popup',
                    title: 'swal-update-title',
                    htmlContainer: 'swal-update-html',
                    confirmButton: 'swal-update-confirm',
                    cancelButton: 'swal-update-cancel'
                }
            }).then(function(result){
                if (result.isConfirmed) {
                    form.dataset.updateConfirmed = 'true';
                    form.submit();
                }
            });

            return false;
        });
    }

    [oldPassword, newPassword, confirmPassword].forEach(function(input){
        input.addEventListener('input', function(){
            updatePasswordStrength();
            validatePasswordForm(false);
        });

        input.addEventListener('blur', function(){
            validatePasswordForm(true);
        });
    });

    if (resetBtn) {
        resetBtn.addEventListener('click', function(){
            resetPasswordForm();
        });
    }

    initPasswordToggle();
    initSubmitConfirmation();
    updatePasswordStrength();
    validatePasswordForm(false);
})();
JS;

$this->registerJs($js, View::POS_END);
?>
